$ErrorActionPreference = 'Stop'
$tempRoot = Join-Path ([IO.Path]::GetTempPath()) ('flit-tunnel-test-' + [guid]::NewGuid().ToString('N'))
[IO.Directory]::CreateDirectory($tempRoot) | Out-Null
try {
    . (Join-Path $PSScriptRoot '..\scripts\watch_tunnel.ps1') -Logs $tempRoot `
        -Exe 'C:\test folder\cloudflared.exe' -Config 'C:\test folder\config.yml'
    $script:fixture = [pscustomobject]@{ ProcessId = 123; CreationDate = Get-Date;
        ExecutablePath = $Exe; CommandLine = '"C:\test folder\cloudflared.exe" --config "C:\test folder\config.yml" tunnel --metrics 127.0.0.1:0 run' }
    if (-not (Test-TunnelIdentity $fixture)) { throw 'Valid tunnel with quoted paths was rejected' }
    $fixture.CommandLine = 'cloudflared --config "C:\test folder\other.yml" tunnel run'
    if (Test-TunnelIdentity $fixture) { throw 'Unrelated tunnel accepted' }
    $fixture.CommandLine = 'cloudflared --config "C:\test folder\config.yml" tunnel run'
    if (-not (Test-TunnelIdentity $fixture)) { throw 'Existing tunnel cannot be adopted' }
    $fixture.ExecutablePath = 'C:\unrelated.exe'
    if (Test-TunnelIdentity $fixture) { throw 'Reused PID accepted' }
    $fixture.ExecutablePath = $Exe

    function Get-WatchedTunnel { return $script:fixture }
    function Test-TunnelReady($Tunnel) { return $script:ready }
    function Restart-WatchedTunnel($Tunnel) { $script:restarts += 1 }
    function New-TestState { return @{ LastProcessId = 123; Failures = 0; HealthyChecks = 0;
        Backoff = 5; NextStart = [datetime]::MinValue; GraceUntil = [datetime]::MinValue } }
    $script:restarts = 0
    $script:ready = $false
    $now = [datetime]::UtcNow
    $state = New-TestState
    Invoke-TunnelWatchCycle $state $now
    Invoke-TunnelWatchCycle $state $now.AddSeconds(30)
    if ($restarts -ne 0) { throw 'Short connection loss caused a restart' }
    $script:ready = $true
    Invoke-TunnelWatchCycle $state $now.AddSeconds(60)
    if ($state.Failures -ne 0 -or $restarts -ne 0) { throw 'Transient failure was not cleared' }

    $script:ready = $false
    1..3 | ForEach-Object { Invoke-TunnelWatchCycle $state $now.AddSeconds(60 + 30 * $_) }
    if ($restarts -ne 1) { throw 'Three consecutive failures did not recover the tunnel' }

    $state = New-TestState
    $state.LastProcessId = 0
    Invoke-TunnelWatchCycle $state $now
    Invoke-TunnelWatchCycle $state $now.AddSeconds(30)
    if ($state.Failures -ne 0 -or $restarts -ne 1) { throw 'Startup grace was not respected' }
    $script:fixture = $null
    $state = New-TestState
    Invoke-TunnelWatchCycle $state $now
    if ($restarts -ne 2) { throw 'Exited process was not recovered' }
    Invoke-TunnelWatchCycle $state $now.AddSeconds(1)
    if ($restarts -ne 2) { throw 'Restart cooldown was ignored' }
    1..10 | ForEach-Object { Invoke-TunnelWatchCycle $state $now.AddSeconds($_ * 600) }
    if ($state.Backoff -ne 300) { throw 'Restart backoff must be capped at five minutes' }

    $before = $restarts
    [IO.File]::WriteAllText($pauseFile, '')
    Invoke-TunnelWatchCycle $state $now.AddDays(1)
    if ($restarts -ne $before) { throw 'Maintenance pause was ignored' }
    Write-Output 'Tunnel watchdog tests passed: identity, transient loss, persistent loss, grace, exit, cooldown and pause.'
} finally {
    # Delete only files generated by this test, without recursive deletion.
    foreach ($name in @('cloudflared.pid', 'tunnel-watchdog.paused')) {
        Remove-Item -LiteralPath (Join-Path $tempRoot $name) -Force -ErrorAction SilentlyContinue
    }
    Remove-Item -LiteralPath $tempRoot -Force
}
