package com.flitfancy.mobile

import org.json.JSONObject
import org.junit.Assert.*
import org.junit.Test

/** Input is generated by the firmware's production encoder, not a second JSON implementation. */
class FirmwareFixtureTest {
    @Test fun `firmware encoder output is accepted by the shipping BLE reader and CH6 parser`() {
        val bytes = javaClass.classLoader!!.getResourceAsStream("phone-ble-firmware-v1.jsonl")!!.use { it.readBytes() }
        val info = BleProtocol.info("""{"model":"FIREFLY-SENSE N16R8","ble_protocol":1,"board_id":"board-A"}""".toByteArray())
        for (size in listOf(20, 244, 512)) {
            val reader = BleProtocol.SnapshotReader(info, 7)
            var result: BleProtocol.Snapshot? = null
            for (offset in bytes.indices step size) result = reader.accept(bytes.copyOfRange(offset, minOf(offset + size, bytes.size)), 1700000000000) ?: result
            val snapshot = result!!
            val frame = SampleCodec.parse(snapshot.rows.single(), snapshot.uptime, snapshot.receivedAt, "ble:${snapshot.boardId}:${snapshot.bootId}", "FIREFLY-SENSE")!!
            val row = JSONObject(frame.payload)
            assertEquals(76, row.getInt("heart_rate_bpm"))
            assertEquals("CH6 \"BLE\" \\ 心率", row.getString("sensor"))
            assertEquals("1.3.6", row.getString("firmware_version"))
            assertEquals(1699999995000, frame.emittedAt)
        }
    }
}
